[package]
name = "hermit-liteinst-runtime-artifact"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
reverie-liteinst = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "025d37800d347c32711038bd0a3889e8e4774c2b", default-features = false, features = ["preload-constructor"] }
