[package]
name = "hermit-liteinst-runtime-artifact"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
reverie-liteinst = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "429962666ad7e9ef05877b74b585a571f57ef0c4", default-features = false, features = ["preload-constructor"] }
