[package]
name = "hermit-liteinst-runtime-artifact"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
reverie-liteinst = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "c261050cfd41bec67e31bfd0cf6f56be008d0ebb", default-features = false, features = ["preload-constructor"] }
