load("@shim//tools/build_defs:rust_library.bzl", "rust_library")

oncall("open_source")

rust_library(
    name = "build_info",
    srcs = ["src/lib.rs"],
    crate = "build_info",
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
)
