[package]
name = "detcore-dbi"
version = "0.0.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
detcore = { version = "0.0.0", path = "../detcore" }
hermit-resources = { version = "0.0.0", path = "../hermit-resources" }
libc = "0.2.186"
rand = "0.10.2"
reverie = { version = "0.1.0", git = "https://github.com/rrnewton/reverie.git", rev = "28d8ba65dbe677d0a3700c51c188eef3f3326167" }
reverie-dbi = { version = "0.1.0", git = "https://github.com/rrnewton/reverie.git", rev = "28d8ba65dbe677d0a3700c51c188eef3f3326167", default-features = false }
serde_json = { version = "1.0.140", features = ["alloc", "float_roundtrip", "raw_value", "unbounded_depth"] }
tracing = "0.1.41"
