[workspace]
members = [
  "common/digest",
  "common/edit-distance",
  "common/test-allocator",
  "ci/manifest-plan",
  "detcore",
  "detcore-model",
  "detcore-dbi",
  "detcore-sabre",
  "detcore/tests/testutils",
  "flaky-tests",
  "hermit-cli",
  "hermit-install",
  "hermit-resources",
  "hermit-verify",
  "tests",
]
resolver = "2"

[workspace.package]
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
