[package]
name = "hermit-install"
version = "0.2.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
publish = false

[lib]
path = "src/lib.rs"

[build-dependencies]
reverie-dbi = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "108f9ab47605a7a2e8ae40353fde21f8a8b2310c", default-features = false }
