[package]
name = "hermit-install"
version = "0.2.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
publish = false

[lib]
path = "src/lib.rs"

[build-dependencies]
reverie-dbi = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "038e993926e45514264d30367b70df9b6ac3b9b8", default-features = false }
