[workspace]
resolver = "3"
members = ["runtime"]
default-members = ["."]

[package]
name = "hermit-liteinst-runtime-build"
version = "0.2.0"
edition = "2024"
publish = false

[lib]
crate-type = ["rlib"]

[build-dependencies]
goblin = "0.10.7"
serde_json = "1.0.151"

[dev-dependencies]
serde_json = "1.0.151"
