[package]
name = "hermit-manifest-plan"
version = "0.2.0"
edition = "2021"
publish = false
default-run = "hermit-manifest-plan"

[dependencies]
dagrun = { path = "../../agent-utils/rs/dagrun" }
detcore-model = { version = "0.2.0", path = "../../detcore-model" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
sha2 = "0.10.9"
shell-words = "1.1.1"
libc = "0.2.186"

[dev-dependencies]
toml = "0.8.23"
