load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("hermit")

rust_library(
    name = "hermit-test-workdir",
    srcs = ["src/lib.rs"],
    autocargo = {"cargo_toml_dir": "."},
    deps = ["fbsource//third-party/rust:libc"],
)

rust_binary(
    name = "workdir-control",
    srcs = ["src/bin/workdir-control.rs"],
    autocargo = {"cargo_toml_dir": "."},
    deps = [":hermit-test-workdir", "fbsource//third-party/rust:libc"],
)
